# Generated by Django 3.2 on 2023-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Уникальный код'),
        ),
    ]
